# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d60cuK2Ig96TZHTQZj0k09vXRMXFUTNd

## DS200: Introduction to Data Sciences
# Lab Assignment 10: Neural Networks (2 points)

In this lab assignment, we will experiment with applying neural networks to an image-recognition task: recognizing handwritten digits.

As usual, let's begin by importing our favorite modules and setting up plots to be displayed in the notebook:
"""

# Commented out IPython magic to ensure Python compatibility.
from datascience import *
import numpy as np

import matplotlib
matplotlib.use('Agg')
# %matplotlib inline
import matplotlib.pyplot as plots

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# jupyter nbconvert --to html /content/Lab10.ipynb

"""Next, we need to load our dataset. For this assignment, we will use a famous benchmark dataset, the [MNIST database](https://en.wikipedia.org/wiki/MNIST_database). This dataset consists of 70,000 images of handwritten digits (see a sample [here](https://upload.wikimedia.org/wikipedia/commons/2/27/MnistExamples.png)), which have all been manually labeled with numbers from 0 to 9.

To load this dataset, we can use a built-in function from the scikit-learn library, `fetch_openml`, which will retrieve the dataset from an online repository. Note that this may take a minute or so in Google Colab due to the size of the dataset. We store the features and corresponding labels in two NumPy arrays, `X_raw` and `y_raw`:
"""

from sklearn.datasets import fetch_openml
X_raw, y_raw = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)

"""# Part 1: Data Exploration

Before attempting to train any models, let's investigate the dataset that we just loaded. First, let's take a look at the feature values `X_raw`, which are stored in an array:
"""

X_raw

"""A bunch of zeros... not very helpful. Let's take a look at the shape of the array `X_raw`:"""

X_raw.shape

"""We see two values, indicating that `X_raw` is a two-dimensional array, that is, an array of arrays. The first number is 70,000, which is the number of examples in the dataset. The second number is 784, which is the number of features. That is a lot of features!

We will get back to these features soon, but before that, let's take a look at the label values `y_raw`:
"""

y_raw

"""We can see numbers, ranging from 0 to 9. This make sense since the dataset consists of handwritten digits (0-9). We can also take a look at the shape of the array `y_raw`:"""

y_raw.shape

"""We see that `y_raw` is a simple, one-dimensional array: one label value for each example.

Now, let's get back to the features. First, let's display the feature values of the first example in the dataset (note that in Python, arrays are indexed starting from 0, so the index of the first example is 0):
"""

X_raw[0]

"""We see a bunch of numbers, which are mostly zero, with a few larger values scattered around. What is the meaning of this?

The numbers that we see above are **image data**, which is not easy for humans to read in their raw form. The data will make much more sense if we display the first example `X_raw[0]` as an image:
"""

plots.imshow(X_raw[0].reshape(28, 28), cmap='binary')
plots.show()

"""Nice. This looks like the digit 5. We can also check the corresponding label to be sure:"""

y_raw[0]

"""Okay, the label also says 5.

So, how is the above image represented by 784 features? To answer this, we need to understand the basics of how digital images are stored by computers, phones, etc. The most common way to represent 2D images digitally is using [raster graphics](https://en.wikipedia.org/wiki/Raster_graphics) (e.g., JPEG and PNG files, but even video frames). A raster graphic represent a 2D image as a rectangular grid of square pixels. Each small square in the above image is one pixel.

You may have noticed that our image looks "blocky" (i.e., like Minecraft). The reason for this is that our image consists of only 28 by 28 pixels (28 rows and 28 columns), and each pixel is a uniformly colored square.

The image data `X_raw[0]` specifies the color of each pixel: 28 rows by 28 columns = 28 * 28 = 784 pixels. The 784 features specify the colors of the 784 pixels.

Finally, let's look at the individual feature values, which are supposed to represent colors:
"""

print("Pixel values")
print("Minimum:", np.min(X_raw))
print("Mean:", np.mean(X_raw))
print("Maximum:", np.max(X_raw))
print("Std.dev.:", np.std(X_raw))

"""We see that feature values range from 0 to 255, and most values are 0 (or close to 0).

You may have also noticed that our image is grayscale: it has only black, white, and various shades of gray in between. This simplifies the representation since for each pixel, we need to store only its brightness, which can be represented by a single number. In this dataset, 0 represents white, 255 represents black, and values in between represent gray pixels (lower values being brighter, and higher values being darker).

### Problem 1: Display Multiple Images from the Dataset [0.3 points]

Write a `for` loop to display the first 10 images in the dataset. For each image, first print the corresponding label, then display the image (see code above for help).

*Hint: The correct output looks like [this](https://drive.google.com/file/d/1YydCJzY6wSXoazjXfXbLxnYkDwDYvxeN/view?usp=share_link) (but for all 10 images). You can use `np.arange(10)`.*
"""

for i in np.arange(10):
  print('Label:', y_raw[i])
  plots.imshow(X_raw[i].reshape(28, 28), cmap='binary')
  plots.show()

"""# Part 2: Preparation of Training and Test Sets

Now that we are familar with the dataset, let's start preparing it for training. First, we need to normalize the feature values (this is always a good idea before training):
"""

X = (X_raw - np.mean(X_raw)) / np.std(X_raw)

"""We can verify that the array `X` has zero mean and unit std. dev.:"""

print("Feature mean:", np.mean(X))
print("Feature std. dev.:", np.std(X))

"""Nice.

Next, let's take a look at the label values:
"""

print("Labels:", y_raw)

"""We see that labels are represented as strings, not numbers (notice the quotation marks ' around the numbers). While this would not pose a challenge for most classification algorithms, it will simpler if we convert the labels to integers:"""

y = y_raw.astype(int)

"""We can verify that the array `y` consists of integer values:"""

print("Labels:", y)

"""All that remains is to randomly split our dataset into a traning and a test set (we will not need a validation set in this assignment because we will not be tweaking hyperparamters). Since we are already familiar with the theory behind this, we can save time by invoking a built-in scikit-learn function to perform the split:"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

"""Function `train_test_split` randomly shuffles the features `X` along with their corresponding labels `y`, and then assigns `train_size` fraction of the examples to a training set and the remaining examples to a test set. In this case, we assigned 80% of the dataset to our training set `X_train` and `y_train`, and the remaining 20% to our test set `X_test` and `y_test`.

We can verify that the training and test arrays have the right shapes:
"""

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

"""The training set has 56,000 examples, while the test set has 14,000 examples. Examples in both sets have 784 features.

### Problem 2: Distribution of Labels in the Training and Test Sets [0.5 points]

Let's verify that the split was indeed random by comparing the distribution of the labels in the training and test sets.

Create two bar plots: one showing the number of examples for each digit (0-9) in the training set; and one showing the same for the test set. Specifically,
* create a table with one column, named `Label`, which contains the label values `y_train`;
* group the rows of the table by label value, counting the number of rows for each distinct value (using the table function `group`);
* display a bar plot with the label values on the horizontal axis;
* repeat the above steps for `y_test`.

*Hint: The correct output looks similar to [this](https://drive.google.com/file/d/1eMSlOoha0Yjpq1HkYrhSyvtLsnL17aKB/view?usp=share_link). Note that due to the random shuffling, there may be minor variations.*
"""

train_table = Table().with_columns('Label', y_train)
train_table.group('Label').bar('Label')

test_table = Table().with_columns('Label', y_test)
test_table.group('Label').bar('Label')

"""We can see that the distribution of labels is roughly the same in the training and test sets.

# Part 3: Training

Now that our training and test sets are ready, we can train a neural network to perform image recognition, specifically, to recognize handwritten digits. In this assignment, we will use a simple feed-forward network with only one hidden layer:
"""

from sklearn.neural_network import MLPClassifier

neural_network = MLPClassifier(hidden_layer_sizes=(5))
neural_network.fit(X_train, y_train)

"""Training this model takes only a minute or so since the model is really simple: it consists of only 5 hidden neurons. Applying the model to our test set takes even less time:"""

y_pred = neural_network.predict(X_test)

"""### Problem 3: Neural Network Training [0.2 points]

Train a neural network with **400** hidden neurons on `X_train` and `y_train`, apply it to `X_test` to obtain predicted labels `y_pred`, and calculate and print the accuracy of the predictions by comparing `y_pred` to `y_test`. Training should take around 5 minutes (or less) in Google Colab.

*Hint: Accuracy may vary depending on the random split into training and test sets as well as depending on the random initialization of the network parameters, but it should typically be around 97-99%. If accuracy is low, you can try to run the training again a couple of times.*
"""

neural_network = MLPClassifier(hidden_layer_sizes=(400))
neural_network.fit(X_train, y_train)

y_pred = neural_network.predict(X_test)

pred_accuracy = sum(y_pred == y_test) / len(y_test)
print('Prediction Accuracy:', pred_accuracy)

"""# Part 4: Evaluation

Beyond measuring simple accuracy, we may also be interested in the typical mistakes that our classifier makes. A standard way of displaying this information is using a [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix) (please make sure that the predictions `y_pred` are from the larger, more accurate model that you trained):
"""

from sklearn.metrics import ConfusionMatrixDisplay
ConfusionMatrixDisplay.from_predictions(y_test, y_pred)

"""The rows of the confusion matrix represent the actual (true) labels, while the columns represent the predicted labels (from our classifier). The diagonal, where the actual and predicted labels are the same, represents correct predictions. The numbers show how many test examples fall into each category. For example, the first number in the first row is the number of test examples where both the actual and predicted label are 0; the second number in the first row is the number of examples where the actual label is 0, but the predicted label is 1; the first number in the second row is the number of test examples where the actual label is 1, but the predicted label is 0; and so on.

Fortunately, the highest number in each row is on the diagonal, which means that most test examples are correctly recognized by our model. The confusion matrix can help us identify which digits are difficult to recognize, and what the typical mistakes are.

### Problem 4: Find and Display Misclassified Digits [0.5 points]

Let's take a look at the test examples that confused our model the most.

First, find the highest off-diagonal number in the confusion matrix (or you can just pick any high number that is not on the diagonal) and write down the `actual_label` and `predicted_label` of this type of mistake. For example, if the highest number is in row 3 and column 8, then `actual_label = 3` and `predicted_label = 8` (which represents mistaking a 3 for an 8).

Second, write code to iterate over the test set (you can use `np.arange(len(y_test))`), and if `y_test[i]` is equal to `actual_label` and `y_pred[i]` is equal to `predicted_label`, then display the image of this example (`imshow(X_test[i].reshape(28, 28), cmap='binary')`).

*Hint: You should have digits displayed similar to Problem 1, one image below the other. You should have as many images as the corresponding number in the confusion matrix.*
"""

actual_label = 3
predicted_label = 8

for i in np.arange(len(y_test)):
  if y_test[i] == actual_label and y_pred[i] == predicted_label:
    plots.imshow(X_test[i].reshape(28,28), cmap='binary')
    plots.show()

"""# Part 5: Comparison

We conclude this lab assignment by comparing our neural network with two other models: an XGBoost decision tree and a *k*-nearest neighbor classifier.

### Problem 5: Comparison wiht Other Classifiers [0.5 points]

Train an XGBoost and a *k*-nearest neighbor classifier using scikit-learn on `X_train` and `y_train`, then apply them to `X_test` and `y_test` to obtain predictions `y_pred`, and calculate and print the accuracy of the classifiers (by comparing `y_pred` to `y_test`). For a sample, see the relevant demo of Lecture 14.

Since this is a large dataset, XGBoost training may take a very long time. To speed the training up, we can restrict XGBoost to train at most 50 trees (note that this will limit its accuracy). To do this, we can specify `n_estimators=50` when creating the classifier object (i.e., `XGBClassifier(n_estimators=50)`). Training XGBoost should take around 5 minutes (or less) in Google Colab.
"""

from xgboost import XGBClassifier
xgboost_mod = XGBClassifier(n_estimators=50)
xgboost_mod.fit(X_train, y_train)
y_pred = xgboost_mod.predict(X_test)
xgb_accuracy = sum(y_test == y_pred) / len(y_pred)
print('Accuracy:', xgb_accuracy)

from sklearn.neighbors import KNeighborsClassifier
k_near_neigh = KNeighborsClassifier()
k_near_neigh.fit(X_train, y_train)
y_pred = k_near_neigh.predict(X_test)
k_accuracy = sum(y_test == y_pred) / len(y_pred)
print('Accuracy:', k_accuracy)